services:
  server:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    depends_on:
      - db

  pma:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    links:
      - db:db

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
